### ISSUE TITLE
[Feature request] Add functionality to encode streams (in addition to support encoding of variables, files or raw byte ranges)

### ISSUE THREAD

**Issue by KurtPfeifle** [jesparza/peepdf#37]
I would like to have a functionality in PeepDF which allows to encode ***streams***. Currently, it is only possible to filter/encode ***variables***, ***files*** and ***raw byte ranges***:

~~~
PPDF> encode help

Usage: encode variable $var_name $filter1 [$filter2 ...]
Usage: encode file $file_name $filter1 [$filter2 ...]
Usage: encode raw $offset $num_bytes $filter1 [$filter2 ...]

Encodes the content of the specified variable, file or raw bytes using the following 
filters or algorithms:
[....]
~~~

So it would be nice to have this:

~~~
PPDF> encode help

Usage: encode variable $var_name $filter1 [$filter2 ...]
Usage: encode file $file_name $filter1 [$filter2 ...]
Usage: encode raw $offset $num_bytes $filter1 [$filter2 ...]
Usage: encode stream $object $filter1 [$filter2 ...]

Encodes the content of the specified variable, file, raw bytes or stream from $object 
using the following filters or algorithms:
[....]
~~~

Of course, re-directing the output of that function to a file should also work:

~~~~
PPDF>  encode stream 9 lzw ahx > stream9-lzw-ahx.txt
~~~~

I know I can work around this by using `encode variables`, `encode file` or `encode raw`. But this requires to go the troublesome path of putting the current stream content into a file or variable first, or of calculating the offset to the stream and its length beforehand....

**Comment by jesparza** [comment]
Hi Kurt!

Did you check the filter command? Is that what you are looking for? The filter command changes the stream filters in a stream object, modifying the stream accordingly and it will write the result in console so you could also redirect the output. In this case it will include also the stream dictionary, are you looking for just encode the stream content? In this case, are you looking for encoding the decoded stream content or the raw stream content?

**Comment by KurtPfeifle** [comment]
Hi Jose,

yes, I want to just encode the stream content and not the stream dictionary. Once the stream got encoded the `/Filter` key in the dict should be updated accordingly to correctly describe what changed for the stream.

I'd like to see various encoding options: for decoded stream content as well as for raw stream content. (When further encoding an already encoded stream the `/Filter` entry should be updated accordingly too, of course).

**Comment by jesparza** [comment]
Mmm, check the filter command, please ;) Maybe that's what you want...:)

**Comment by jesparza** [comment]
I am resolving this issue, because the filter command should do what @KurtPfeifle is asking ;)
