### ISSUE TITLE
[Feature request] Add a `-C cmd1,cmd2,cmd3` command line option to peepdf

### ISSUE THREAD

**Issue by KurtPfeifle** [jesparza/peepdf#39]
Currently one can run `peepdf.py -s script my.pdf` and have PeepDF.py execute the commands listed in the`script` file without a need to start it in interactive mode.

It would be nice if we had a more direct way to execute one or more small commands like this:

~~~
 peepdf.py -C "tree,offsets,filters 9" my.pdf
 peepdf.py --commands "tree,offsets,filters 9" my.pdf
~~~

This should then behave the same as running `peepdf.py -s script` where the contents of script was:

~~~ 
tree
offsets
filters 9
~~~

This feature would save us from the sometimes long-winded path of first creating or editing/modifying a `script` file.

**Comment by jesparza** [comment]
Hey @KurtPfeifle! I checked PR #49 and I modified it to avoid writing on disk and other improvements. Anyway, now this is supported, but the syntax would be:

peepdf.py -C tree -C offsets -C "filters 9" my.pdf

Probably, I will improve this basic implementation in the next days...
