### ISSUE TITLE
referenced before assignment

### ISSUE THREAD

**Issue by neonnds** [jesparza/peepdf#43]
UnboundLocalError: local variable 'userPass' referenced before assignment on line 260 of PDFCrypto.py

**Comment by jesparza** [comment]
I was checking this error and I did not find the bug. Line 260 should be function isOwnerPass and I did not find any reference to that variable in the PDFCrypto.py version available on the created issue date. My guess is that you were using an old version? :? Just in case, I modified function computeUserPass that could lead to a similar error.
