### ISSUE TITLE
PyV8 no longer buildable

### ISSUE THREAD

**Issue by seanthegeek** [jesparza/peepdf#55]
Pyv8 is now no longer hosted on Google code or supported. All of the old mirrors people have made on github will not build. Maybe switch to a new library?

**Comment by jesparza** [comment]
Hi!

Did you check the one maintained by @buffer?

https://github.com/buffer/pyv8

**Comment by seanthegeek** [comment]
That one built fine. Thanks! Maybe that sould be added to the docs.
