### ISSUE TITLE
KeyError: URIs

### ISSUE THREAD

**Issue by jdubp** [jesparza/peepdf#64]
Any idea what is causing this error. I tried python2 peepdf.py --update and the code is up to date. This is happening on Linux.

peepdf.py", line 626, in <module>
    stats += beforeStaticLabel + 'URIs: ' + resetColor + statsDict['URIs'] + newLine
KeyError: 'URIs'

**Comment by jesparza** [comment]
Hi @cyber-guy,

Can you tell me the peepdf version you are using and the exact command line, please?

Thanks!

**Comment by jdubp** [comment]
Thanks for looking into this. The error was occuring on peepdf 0.3 r275 when simply running peepdf.py -f <file>. I had an older copy of peepdf r248 so reverted back to that and the issue went away. For some reason i'm unable to reproduce the error now after updating back to r275. It could have been a modification i made (i think i had added /URI to the PDFCore.py file for monitorizedElements).

I believe the issue was with the modification i made, sorry for the confusion.

**Comment by jesparza** [comment]
No worries, thanks!
