### ISSUE TITLE
using peepdf in python programming

### ISSUE THREAD

**Issue by palak-sethia** [jesparza/peepdf#65]
@jesparza As this is a python tool. Can you tell if I can use its commands in python programming by importing peepdf as a package. 
I have analysed my pdf and had a look at its all objects by executing console commands like object 1, object 2 etc. Now my goal is to replace the content of 24 numbered object. Is that possible with this? 
Please suggest.

**Comment by jesparza** [comment]
Hi @shahpalak02,

You can use the PyPi package created by @jbremer and import peepdf as a package. This will be merged to master somewhere in 2017:

https://pypi.python.org/pypi/peepdf/0.3.3

Depending on what you want to put in object 24 you could do something like it is done with the "modify" command (PDFConsole.modifyObject). I hope this helps!
